name: Release

on: 
  push:
    tags:
    - '*'

jobs:

  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - uses: montudor/action-zip@v0.1.1
        with:
          args: zip -qq -r release.zip ./*
    
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "release.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
        
